<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-HT8QQFT" failures="1" tests="2" name="Test(failed)" time="0.114" errors="0" timestamp="2022-03-20T12:55:57 IST">
  <testcase classname="TestNG.example9_sample2" name="TC6" time="0.02">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at TestNG.example9_sample2.TC6(example9_sample2.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- TC6 -->
  <testcase classname="TestNG.example9_sample1" name="TC3" time="0.003"/>
  <testcase classname="TestNG.example9_sample1" name="TC1" time="0.0">
    <ignored/>
  </testcase> <!-- TC1 -->
  <testcase classname="TestNG.example9_sample2" name="TC4" time="0.0">
    <ignored/>
  </testcase> <!-- TC4 -->
  <testcase classname="TestNG.example9_sample2" name="TC5" time="0.0">
    <ignored/>
  </testcase> <!-- TC5 -->
  <testcase classname="TestNG.example9_sample1" name="TC2" time="0.0">
    <ignored/>
  </testcase> <!-- TC2 -->
</testsuite> <!-- Test(failed) -->
